version: "3.7"

services:
    Backend:
        container_name: Backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - app
        env_file: .env
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        container_name: database
        env_file: .env
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=foodart
        ports:
            - "5432:5432"
        networks:
            - app
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:

networks:
    app:
        driver: bridge
